name: Validations
on: [push, pull_request]

jobs:
  valitdations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install the project
        run: uv sync

      - name: Run Ruff
        run: uv run ruff check --output-format=github ./src
          
      - name: Run tests
        run: uv run pytest

      - name: Build Docker image
        run: docker build -t vectrix-graphs .
