name: Validations
on: [push, pull_request]

jobs:
  valitdations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install --system-packages
          
      - name: Install the project
        run: uv sync

      - name: Run Ruff
        run: uv run ruff check --output-format=github ./src
          
      - name: Run tests
        run: uv run pytest

      - name: Build Docker image
        run: docker build -t vectrix-graphs .
